// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ShowTweetController from "./show_tweet_controller"
application.register("show_tweet", ShowTweetController)

import TweetsController from "./tweets_controller"
application.register("tweets", TweetsController)
