# inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 3.2.1
  Exclude:
    - Gemfile
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

## Disable most Metrics/*Length cops
# Reason: those are often triggered and force significant refactors and
# dosen't really improve the code quality.

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsblocklength
Metrics/BlockLength:
  Enabled: false
  AllowedMethods: ['describe', 'context']

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsclasslength
Metrics/ClassLength:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsmethodlength
Metrics/MethodLength:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_metrics.html#metricsmodulelength
Metrics/ModuleLength:
  Enabled: false


Layout/FirstArgumentIndentation:
  Exclude:
    - spec/controllers/api/payments_controller_spec.rb