# fly.toml app configuration file generated for churp-app on 2023-10-20T22:22:42-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "churp-app"
primary_region = "yyz"
console_command = "/rails/bin/rails console"
kill_signal = "SIGINT"
kill_timeout = "10s"
swap_size_mb = 512

[build]

[processes]
  app = "./bin/rails server"
  sidekiq = "bundle exec sidekiq"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.status]
    port = 3000
    type = "http"
    interval = "10s"
    timeout = "10s"
    grace_period = "5s"
    method = "GET"
    path = "/up"
    protocol = "http"
    tls_skip_verify = false
    [checks.status.headers]
      X-Forwarded-Proto = "https"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
