default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: churp_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: churp_test
  username: postgres
  password: postgres
  host: localhost

production:
  <<: *default
  database: churp_production
  username: churp
  password: <%= ENV["CHURP_DATABASE_PASSWORD"] %>
