default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: churp_development
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV['DATABASE_HOST'] %>

test:
  <<: *default
  database: churp_test
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: <%= ENV['DATABASE_HOST'] %>

production:
  <<: *default
  database: churp_production
  username: churp
  password: <%= ENV["CHURP_DATABASE_PASSWORD"] %>
