service: churp-app
image: tonylombardi/churp-app

servers:
  web:
    - 165.22.46.224

registry:
  username: tonylombardi
  password:
    - DOCKER_REGISTRY_TOKEN

# Container builder setup.
builder:
  args:
    RUBY_VERSION: 3.2.1
    RAILS_ENV: production
    NODE_VERSION: 18.12.0
    YARN_VERSION: 1.22.19
  multiarch: false
  # cache:
  #   type: registry
  #   image: onetribe-build-cache
  #   options: mode=max,image-manifest=true,oci-mediatypes=true

# Container run setup
env:
  clear:
    RAILS_LOG_TO_STDOUT: 1
    RAILS_SERVE_STATIC_FILES: 1
    RAILS_ENV: production
  secret:
    - RAILS_MASTER_KEY
    # - DATABASE_URL
    - REDIS_URL

env:
  clear:
    DB_HOST: 165.22.46.224
  secret:
    - RAILS_MASTER_KEY
    # - DATABASE_URL
    - REDIS_URL

accessories:
  db:
    image: postgres:15
    host: 165.22.46.224
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'churp'
        POSTGRES_DB: 'churp_production'
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data

# Configure custom arguments for Traefik
traefik:
  args:
    accesslog: true
    accesslog.format: json

  # Configure a custom healthcheck (default is /up on port 3000)
  healthcheck:
    cmd: ls -l > /dev/null
    interval: 20s
